#!/usr/bin/env python3
"""Warm vs cold on a real project: does mcp-rector-warm give the same answers as a
fresh `rector process`?

    tools/warm-vs-cold.py --project DIR --files 'src/**/*.php' --out OUT [options]

Warm side: ONE mcp-rector-warm session over stdio, driven by the official Python MCP
client (as tests/E2E does), calling rector_process with dryRun: true on each file in
order. Cold side: a fresh `rector process --dry-run` per file, --jobs at a time. Both
sides use the flags RectorTool::process() passes, and a generated wrapper config that
`require`s --config exactly once and points Rector's cache at a scratch directory (one
for warm, one per cold process), so the project's own cache is neither written nor
able to mask a difference.

Every call is a dry run. Nothing in this script can apply a change.

Modes (the report labels which one ran):
  checkout        this checkout's bin/ and vendor/ (vendor/bin/rector for cold).
  project-vendor  --project-autoload PATH: emulate a project-dependency install --
                  this checkout's bin/ and src/ on top of the project's own Composer
                  autoloader, and the rector next to that autoloader for cold. This is
                  how a project that has the package in require-dev runs it.

Writes to --out: report.json, report.md, files.txt, warm-server.stderr, the wrapper
config, the Rector caches, and (project-vendor) the shim.
Exit status: 0 all match, 1 at least one mismatch, 2 no mismatch but a side errored.
"""

from __future__ import annotations

import argparse
import asyncio
import glob
import hashlib
import json
import os
import platform
import random
import re
import shutil
import statistics
import subprocess
import sys
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tests" / "E2E"))

from mcp import ClientSession, StdioServerParameters  # noqa: E402
from mcp.client.stdio import stdio_client  # noqa: E402
from mcp.types import Implementation  # noqa: E402

from mcp_harness import normalise, rector_report, structured  # noqa: E402

# What RectorTool::process() builds for a dry run, minus the trailing '--' + path.
RECTOR_FLAGS = ["process", "--output-format=json", "--debug", "--no-progress-bar", "--dry-run"]
CACHE_ENV = "WARM_VS_COLD_CACHE_DIR"

# Loads the real config once and overrides only its cache (last withCache() wins).
# A config that declares functions or classes cannot be required twice in one
# process, so nothing here requires it again.
WRAPPER_PHP = r"""<?php
// Generated by tools/warm-vs-cold.py -- scratch file, do not commit.
declare(strict_types=1);

$wvcConfig = require __CONFIG__;
$wvcCacheDir = getenv('WARM_VS_COLD_CACHE_DIR') ?: sys_get_temp_dir() . '/warm-vs-cold-cache';
if ($wvcConfig instanceof \Rector\Configuration\RectorConfigBuilder) {
    return $wvcConfig->withCache($wvcCacheDir, \Rector\Caching\ValueObject\Storage\FileCacheStorage::class);
}
if (is_callable($wvcConfig)) {
    return static function (\Rector\Config\RectorConfig $rectorConfig) use ($wvcConfig, $wvcCacheDir): void {
        $wvcConfig($rectorConfig);
        $rectorConfig->cacheDirectory($wvcCacheDir);
        $rectorConfig->cacheClass(\Rector\Caching\ValueObject\Storage\FileCacheStorage::class);
    };
}
throw new \RuntimeException('warm-vs-cold: the config returned neither a RectorConfigBuilder nor a callable');
"""

# The project's Composer autoloader, then this checkout's src/ prepended for our
# namespace, so an older copy the project has installed never wins.
SHIM_AUTOLOAD_PHP = r"""<?php
// Generated by tools/warm-vs-cold.py -- scratch file, do not commit.
$wvcLoader = require __AUTOLOAD__;
spl_autoload_register(static function (string $class): void {
    $prefix = 'Dpt\\McpRectorWarm\\';
    if (!str_starts_with($class, $prefix)) {
        return;
    }
    $file = __SRC__ . str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
    if (is_file($file)) {
        require $file;
        fwrite(STDERR, "warm-vs-cold shim: {$class} loaded from {$file}\n");
    }
}, true, true);
return $wvcLoader;
"""


def php_str(value: str) -> str:
    """A single-quoted PHP literal: no interpolation; only backslash and quote escaped."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


# --------------------------------------------------------------------------- setup

def write_wrapper_config(config: Path, dest: Path) -> Path:
    dest.write_text(WRAPPER_PHP.replace("__CONFIG__", php_str(str(config))), encoding="utf-8")
    return dest


def build_project_vendor_shim(project_autoload: Path, shim: Path) -> Path:
    """bin/ + src/ + vendor/autoload.php: the checkout's unchanged bin takes its first
    autoload candidate (__DIR__ . '/../vendor/autoload.php'), which is the shim."""
    if shim.exists():
        shutil.rmtree(shim)
    (shim / "bin").mkdir(parents=True)
    (shim / "vendor").mkdir()
    shutil.copy2(REPO / "bin" / "mcp-rector-warm", shim / "bin" / "mcp-rector-warm")
    shutil.copytree(REPO / "src", shim / "src")  # scanned by the SDK's tool discovery
    (shim / "vendor" / "autoload.php").write_text(
        SHIM_AUTOLOAD_PHP.replace("__AUTOLOAD__", php_str(str(project_autoload)))
        .replace("__SRC__", php_str(str(REPO / "src") + "/")),
        encoding="utf-8",
    )
    return shim / "bin" / "mcp-rector-warm"


def select_files(project: Path, specs: list[str], limit: int | None, seed: int) -> tuple[list[Path], int]:
    """Expand --files (globs relative to --project, or @LISTFILE; glob matches come in
    sorted order, a list file in its own order). Under --limit, draw a
    seeded sample spread across directories: shuffle the directories, then take one
    file per directory per round until the limit is reached. The sample order is the
    warm call order."""
    found: dict[Path, None] = dict()  # insertion-ordered set: @LISTFILE order is kept
    for spec in specs:
        if spec.startswith("@"):
            lines = Path(spec[1:]).read_text(encoding="utf-8").splitlines()
            candidates = [project / line.strip() for line in lines if line.strip()]
        else:
            candidates = [Path(p) for p in sorted(glob.glob(str(project / spec), recursive=True))]
        found.update(dict.fromkeys(p.resolve() for p in candidates if p.is_file() and p.suffix == ".php"))
    everything = list(found)
    if limit is None or limit >= len(everything):
        return everything, len(everything)  # listed order: replays a session prefix exactly
    everything.sort()

    rng = random.Random(seed)
    by_dir: dict[Path, list[Path]] = defaultdict(list)
    for path in everything:
        by_dir[path.parent].append(path)
    dirs = sorted(by_dir)
    rng.shuffle(dirs)
    for d in dirs:
        rng.shuffle(by_dir[d])
    picked: list[Path] = []
    while len(picked) < limit:
        for d in dirs:
            if by_dir[d] and len(picked) < limit:
                picked.append(by_dir[d].pop())
    return picked, len(everything)


# --------------------------------------------------------------------------- warm

class _SessionLost(Exception):
    pass


def _warm_failure(session_no: int, seconds: float, message: str, exc: BaseException) -> dict[str, Any]:
    payload = dict(error=f"{message}: {exc!r}", error_class=type(exc).__name__)
    return dict(session=session_no, seconds=seconds, is_error=True, payload=payload)


async def run_warm(args: argparse.Namespace, bin_path: Path, files: list[Path], out: Path) -> list[dict[str, Any]]:
    """One session for the whole list. A call that kills or times out the session is
    recorded as a warm error for that file, and a new session carries on with the
    next one; the report counts sessions, so a restart is never silent."""
    cache_dir = out / "cache" / "warm"
    cache_dir.mkdir(parents=True, exist_ok=True)
    env = dict(os.environ, **{CACHE_ENV: str(cache_dir)})
    argv = [str(bin_path), f"--working-dir={args.working_dir}", f"--config={args.server_config}"]
    params = StdioServerParameters(command=args.php, args=argv, cwd=str(args.working_dir), env=env)
    timeout = args.timeout  # seconds; this mcp client takes a float

    results: list[dict[str, Any]] = []
    session_no = 0
    with open(out / "warm-server.stderr", "w", encoding="utf-8") as errlog:
        while len(results) < len(files):
            session_no += 1
            errlog.write(f"--- warm-vs-cold: session {session_no} starts at file #{len(results)}\n")
            errlog.flush()
            try:
                async with stdio_client(params, errlog=errlog) as (read, write):
                    client_info = Implementation(name="warm-vs-cold", version="1.0.0")
                    async with ClientSession(read, write, client_info=client_info) as session:
                        await session.initialize()
                        while len(results) < len(files):
                            path = files[len(results)]
                            arguments = dict(path=str(path), dryRun=True)
                            started = time.perf_counter()
                            try:
                                result = await session.call_tool("rector_process", arguments, read_timeout_seconds=timeout)
                            except Exception as exc:
                                results.append(_warm_failure(session_no, time.perf_counter() - started, "session lost", exc))
                                raise _SessionLost() from exc
                            seconds = time.perf_counter() - started
                            results.append(dict(session=session_no, seconds=seconds, is_error=bool(result.is_error), payload=structured(result)))
                            if args.progress:
                                print(f"warm {len(results)}/{len(files)} {seconds:7.2f}s {path.name}", file=sys.stderr)
            except (KeyboardInterrupt, SystemExit):
                raise
            except BaseException as exc:  # _SessionLost, or a start/teardown failure
                if not results or results[-1]["session"] != session_no:
                    # Nothing ran in this session: the server never came up. Charge the
                    # file it was about to run, so a server that cannot start ends the loop.
                    results.append(_warm_failure(session_no, 0.0, "session failed to start", exc))
    return results


# --------------------------------------------------------------------------- cold

def run_cold_one(args: argparse.Namespace, rector: Path, path: Path, cache_dir: Path) -> dict[str, Any]:
    cache_dir.mkdir(parents=True, exist_ok=True)
    env = dict(os.environ, **{CACHE_ENV: str(cache_dir)})
    argv = [args.php, str(rector), *RECTOR_FLAGS, f"--config={args.server_config}", "--", str(path)]
    started = time.perf_counter()
    try:
        done = subprocess.run(argv, cwd=args.working_dir, env=env, capture_output=True, text=True, timeout=args.timeout)
        return dict(seconds=time.perf_counter() - started, exit_code=done.returncode, output=done.stdout, stderr=done.stderr[-4000:])
    except subprocess.TimeoutExpired:
        return dict(seconds=time.perf_counter() - started, exit_code=None, output="", stderr=f"timeout after {args.timeout}s")
    except OSError as exc:
        # args.php could not even be spawned (bad path, PATH not set up the way the
        # checkout expects). Report it the same shape as a timeout rather than
        # crashing main() -- a crash here would lose the whole warm phase's results.
        return dict(seconds=time.perf_counter() - started, exit_code=None, output="", stderr=f"could not start {args.php!r}: {exc!r}")


def run_cold(args: argparse.Namespace, rector: Path, files: list[Path], out: Path) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = [dict() for _ in files]
    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futures = dict()
        for i, path in enumerate(files):
            futures[pool.submit(run_cold_one, args, rector, path, out / "cache" / "cold" / str(i))] = i
        for n, future in enumerate(as_completed(futures), 1):
            results[futures[future]] = future.result()
            if args.progress:
                print(f"cold {n}/{len(files)}", file=sys.stderr)
    return results


# --------------------------------------------------------------------------- compare

def summarise_side(payload: dict[str, Any], root: Path) -> dict[str, Any]:
    """normalise() from tests/E2E (exit code, changed files, diffs, errors, with the
    root scrubbed), plus the rules that fired, which is where a reduction starts."""
    report = rector_report(payload.get("output", "") or "")
    diffs = (report or dict()).get("file_diffs", []) or []
    rectors = sorted(set(r for d in diffs for r in d.get("applied_rectors", [])))
    return dict(norm=normalise(payload, root), applied_rectors=rectors, has_report=report is not None)


def compare(files: list[Path], warm: list[dict[str, Any]], cold: list[dict[str, Any]], root: Path) -> list[dict[str, Any]]:
    rows = []
    for path, w, c in zip(files, warm, cold):
        ws = summarise_side(w["payload"], root)
        cs = summarise_side(dict(exit_code=c["exit_code"], output=c["output"]), root)
        warm_failed = w["is_error"] or not ws["has_report"]
        cold_failed = c["exit_code"] is None or not cs["has_report"]
        if warm_failed and cold_failed:
            status = "both_error"
        elif warm_failed:
            status = "warm_error"
        elif cold_failed:
            status = "cold_error"
        else:
            status = "match" if ws["norm"] == cs["norm"] else "mismatch"
        warm_row = dict(
            seconds=round(w["seconds"], 3), session=w["session"],
            changed=bool(ws["norm"].get("diffs")), applied_rectors=ws["applied_rectors"],
            normalised=ws["norm"], error=w["payload"].get("error"), error_class=w["payload"].get("error_class"),
        )
        cold_row = dict(
            seconds=round(c["seconds"], 3),
            changed=bool(cs["norm"].get("diffs")), applied_rectors=cs["applied_rectors"],
            normalised=cs["norm"], stderr_tail=c["stderr"][-1500:] if cold_failed else "",
        )
        rows.append(dict(file=os.path.relpath(path, root), status=status, warm=warm_row, cold=cold_row))
    return rows


def pct(values: list[float], q: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    return round(ordered[max(0, min(len(ordered) - 1, round(q * (len(ordered) - 1))))], 3)


def timing(values: list[float]) -> dict[str, Any]:
    mean = round(statistics.fmean(values), 3) if values else None
    return dict(n=len(values), p50=pct(values, 0.5), p95=pct(values, 0.95), mean=mean, sum=round(sum(values), 3))


def warm_timing_buckets(warm: list[dict[str, Any]]) -> dict[str, list[float]]:
    """warm[0] paid a container boot; so does any later call whose session differs
    from the call right before it (a mid-run restart). Split those into 'first'
    (index 0 only, unchanged meaning) and 'restart_boot' (later boots), so neither
    silently inflates 'later' -- the bucket the docs tell a reader to compare
    against cold per-call timings."""
    boot_idx = {0} | {i for i in range(1, len(warm)) if warm[i]["session"] != warm[i - 1]["session"]}
    return dict(
        first=[warm[0]["seconds"]],
        later=[w["seconds"] for i, w in enumerate(warm) if i not in boot_idx],
        restart_boot=[warm[i]["seconds"] for i in sorted(boot_idx) if i != 0],
    )


def md_fence(*texts: str) -> str:
    """A fenced-code delimiter longer than any run of backticks already inside the
    text, so content from the project under test (a Rector diff, a stderr tail) can
    never close the fence early and let the rest render as raw Markdown."""
    longest = 0
    for text in texts:
        for run in re.findall("`+", text):
            longest = max(longest, len(run))
    return "`" * max(3, longest + 1)


# --------------------------------------------------------------------------- report

def write_markdown(report: dict[str, Any], dest: Path) -> None:
    m, s, t = report["meta"], report["summary"], report["timings"]
    lines = [
        "# warm vs cold", "",
        f"- mode: **{m['mode']}**; checkout HEAD {m['checkout_head']}, src/+bin/ digest {m['code_digest'][:12]}",
        f"- project: `{m['project']}`; config: `{m['config']}`",
        f"- php: `{m['php']}` ({m['php_version']}); platform: {m['platform']}",
        f"- files: {m['sampled']} of {m['candidates']} candidates (seed {m['seed']}, limit {m['limit']}); cold jobs: {m['jobs']}",
        f"- warm sessions: {m['warm_sessions']} (more than 1 means the server was restarted)", "",
        "| match | mismatch | warm error | cold error | both error |",
        "| ---: | ---: | ---: | ---: | ---: |",
        f"| {s['match']} | {s['mismatch']} | {s['warm_error']} | {s['cold_error']} | {s['both_error']} |", "",
        f"Files with a diff (warm / cold): {s['changed_warm']} / {s['changed_cold']}. Rector can list a file under"
        " changed_files with no diff; that list is compared too, but not counted here.", "",
        "## Timings (seconds per call)", "",
        "| side | n | p50 | p95 | mean | sum |", "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    timing_rows = [("warm, first call (includes boot)", "warm_first"), ("warm, later calls", "warm_later")]
    if t["warm_restart_boot"]["n"]:
        timing_rows.append(("warm, right after a restart (boot cost, not in \"later\")", "warm_restart_boot"))
    timing_rows.append(("cold", "cold"))
    for label, key in timing_rows:
        v = t[key]
        lines.append(f"| {label} | {v['n']} | {v['p50']} | {v['p95']} | {v['mean']} | {v['sum']} |")
    lines += ["", f"Wall clock: warm phase {t['warm_wall']} s (serial), cold phase {t['cold_wall']} s ({m['jobs']} jobs).", ""]

    def section(title: str, status: str, body) -> None:
        rows = [r for r in report["files"] if r["status"] == status]
        lines.extend([f"## {title} ({len(rows)})", ""])
        for r in rows:
            lines.extend(body(r))
        lines.append("" if rows else "None.\n")

    def mismatch_body(r):
        out = [f"### `{r['file']}`", "",
               f"- warm rules: {', '.join(r['warm']['applied_rectors']) or 'none'}",
               f"- cold rules: {', '.join(r['cold']['applied_rectors']) or 'none'}", ""]
        for side in ("warm", "cold"):
            n = r[side]["normalised"]
            diff = "\n".join(n.get("diffs", dict()).values()) or "(no diff)"
            fence = md_fence(diff)
            out += [f"{side}: exit {n.get('exit_code')}, errors {json.dumps(n.get('errors'))}", "", f"{fence}diff", diff.rstrip(), fence, ""]
        return out

    def warm_error_body(r):
        return [f"- `{r['file']}`: {r['warm']['error_class']}: {str(r['warm']['error'])[:300]}"]

    def cold_error_body(r):
        return [f"- `{r['file']}`: {r['cold']['stderr_tail'][-300:].strip() or 'no JSON report'}"]

    section("Mismatches", "mismatch", mismatch_body)
    section("Warm errors", "warm_error", warm_error_body)
    section("Cold errors", "cold_error", cold_error_body)
    section("Both sides errored", "both_error", warm_error_body)
    lines += [f"## Matches ({s['match']})", ""]
    lines += [f"- `{r['file']}`{' (changed)' if r['warm']['changed'] else ''}" for r in report["files"] if r["status"] == "match"]
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def checkout_head() -> str:
    """HEAD's commit, read from the repository metadata (works in a linked worktree)."""
    try:
        dot = REPO / ".git"
        meta = Path(dot.read_text().split(":", 1)[1].strip()) if dot.is_file() else dot
        meta = meta if meta.is_absolute() else (REPO / meta).resolve()
        head = (meta / "HEAD").read_text().strip()
        if not head.startswith("ref: "):
            return head
        ref = head[5:]
        common = (meta / (meta / "commondir").read_text().strip()).resolve() if (meta / "commondir").is_file() else meta
        for base in (meta, common):
            if (base / ref).is_file():
                return (base / ref).read_text().strip()
        packed = common / "packed-refs"
        for line in packed.read_text().splitlines() if packed.is_file() else []:
            if line.endswith(" " + ref):
                return line.split()[0]
    except (OSError, IndexError):
        pass
    return "unknown"


def code_digest() -> str:
    """sha256 over bin/ and src/ as they are on disk: names the exact code that ran,
    uncommitted edits included, where HEAD alone would not."""
    h = hashlib.sha256()
    for path in sorted([REPO / "bin" / "mcp-rector-warm", *(REPO / "src").rglob("*.php")]):
        h.update(str(path.relative_to(REPO)).encode() + b"\0" + path.read_bytes())
    return h.hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--project", required=True, type=Path, help="project root; --files globs are relative to it")
    ap.add_argument("--config", type=Path, help="rector config (default: PROJECT/rector.php); never edited")
    ap.add_argument("--working-dir", type=Path, help="cwd of both sides, and the server's --working-dir (default: PROJECT)")
    ap.add_argument("--php", default=os.environ.get("PHP_BINARY") or shutil.which("php") or "php")
    ap.add_argument("--files", action="append", required=True, help="glob relative to PROJECT (** allowed) or @LISTFILE; repeatable")
    ap.add_argument("--limit", type=int, help="sample this many files, spread across directories")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--jobs", type=int, default=max(1, (os.cpu_count() or 2) // 2), help="parallel cold runs")
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--project-autoload", type=Path, help="the project's vendor/autoload.php: run in project-vendor mode")
    ap.add_argument("--rector", type=Path, help="rector binary for the cold side (default: the one the mode implies)")
    ap.add_argument("--timeout", type=float, default=600.0, help="seconds per call, either side")
    ap.add_argument("--progress", action="store_true", help="one line per call on stderr")
    args = ap.parse_args()

    args.project = args.project.resolve()
    args.config = (args.config or args.project / "rector.php").resolve()
    args.working_dir = (args.working_dir or args.project).resolve()
    args.out = args.out.resolve()
    args.out.mkdir(parents=True, exist_ok=True)
    # A stale cache entry from an earlier run into this same --out must never look
    # like a fresh match: force both sides' Rector caches to start empty every run.
    shutil.rmtree(args.out / "cache", ignore_errors=True)
    if args.project_autoload:
        args.project_autoload = args.project_autoload.resolve()
        mode = "project-vendor"
        bin_path = build_project_vendor_shim(args.project_autoload, args.out / "shim")
        rector = args.rector or args.project_autoload.parent / "bin" / "rector"
    else:
        mode = "checkout"
        bin_path = REPO / "bin" / "mcp-rector-warm"
        rector = args.rector or REPO / "vendor" / "bin" / "rector"
    rector = Path(rector).resolve()
    args.server_config = write_wrapper_config(args.config, args.out / "wrapper-rector.php")

    files, candidates = select_files(args.project, args.files, args.limit, args.seed)
    if not files:
        print("warm-vs-cold: --files matched nothing", file=sys.stderr)
        return 2
    (args.out / "files.txt").write_text(
        "\n".join(os.path.relpath(p, args.project) for p in files) + "\n", encoding="utf-8",
    )

    # Serial phases, so neither side's timings carry the other's CPU load.
    t0 = time.perf_counter()
    warm = asyncio.run(run_warm(args, bin_path, files, args.out))
    warm_wall = time.perf_counter() - t0
    t0 = time.perf_counter()
    cold = run_cold(args, rector, files, args.out)
    cold_wall = time.perf_counter() - t0

    rows = compare(files, warm, cold, args.project)
    statuses = ("match", "mismatch", "warm_error", "cold_error", "both_error")
    counts = dict((k, sum(1 for r in rows if r["status"] == k)) for k in statuses)
    counts["changed_warm"] = sum(1 for r in rows if r["warm"]["changed"])
    counts["changed_cold"] = sum(1 for r in rows if r["cold"]["changed"])
    php_version = subprocess.run([args.php, "-r", "echo PHP_VERSION;"], capture_output=True, text=True).stdout.strip()
    stderr_text = (args.out / "warm-server.stderr").read_text(errors="replace")
    shim_lines = sorted(set(line.strip() for line in stderr_text.splitlines() if line.startswith("warm-vs-cold shim:")))
    meta = dict(
        mode=mode, checkout=str(REPO), checkout_head=checkout_head(), code_digest=code_digest(),
        project=str(args.project), config=str(args.config), working_dir=str(args.working_dir),
        php=args.php, php_version=php_version,
        platform=f"{platform.system()} {platform.release()} {platform.machine()}",
        warm_bin=str(bin_path), cold_rector=str(rector), wrapper_config=str(args.server_config),
        project_autoload=str(args.project_autoload) if args.project_autoload else None,
        shim_loaded=shim_lines, files_spec=args.files, seed=args.seed, limit=args.limit,
        jobs=args.jobs, candidates=candidates, sampled=len(files),
        warm_sessions=max(w["session"] for w in warm),
        finished=datetime.now(timezone.utc).isoformat(timespec="seconds"),
    )
    buckets = warm_timing_buckets(warm)
    timings = dict(
        warm_first=timing(buckets["first"]),
        warm_later=timing(buckets["later"]),
        warm_restart_boot=timing(buckets["restart_boot"]),
        cold=timing([c["seconds"] for c in cold]),
        warm_wall=round(warm_wall, 1), cold_wall=round(cold_wall, 1),
    )
    report = dict(meta=meta, summary=counts, timings=timings, files=rows)
    (args.out / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    write_markdown(report, args.out / "report.md")
    print(f"warm-vs-cold [{mode}]: {counts['match']} match, {counts['mismatch']} mismatch, "
          f"{counts['warm_error']} warm error, {counts['cold_error']} cold error, {counts['both_error']} both error"
          f" -> {args.out / 'report.md'}")
    if counts["mismatch"]:
        return 1
    return 2 if counts["warm_error"] or counts["cold_error"] or counts["both_error"] else 0


if __name__ == "__main__":
    sys.exit(main())
